---
 - name: Install nginx reverse proxy
   package:
     name: nginx

 - name: Configure nginx sites
   template:
     src: 'default.j2'
     dest: '/etc/nginx/sites-available/default'
   notify: nginx_restart
