# -*- coding: utf-8 -*-

language: python
sudo: false
cache: pip
python:
  - "2.7"

install:
  - pip install ansible ansible-lint

script:
  - ansible --version
  - ansible-lint --version
  - ansible-lint site.yml
  - ansible-lint local.yml
  - ansible-lint vagrant.yml
  - ansible-playbook site.yml --syntax-check
  - ansible-playbook local.yml --syntax-check
  - ansible-playbook vagrant.yml --syntax-check
  - ansible-playbook local.yml 

# vim: set ts=2 sw=2 tw=2 :
