# -*- coding: utf-8 -*-

language: python
cache: pip
python:
  - "3.6"

install:
  - pip install --upgrade ansible ansible-lint yamllint

before_script:
  - sudo apt-get install -y python3-apt
  - git clone https://github.com/adfinis-sygroup/ansible-lint-rules ../lint-rules
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - ERRORS=0

script:
  - ansible-lint -R -r ../lint-rules . || let ERRORS+=1 ;
  - yamllint -c .testenv/yamllint.yml "$dir" || let ERRORS+=1 ;
  - ansible-playbook -b local.yml || let ERRORS+=1 ;
  - exit $ERRORS

# vim: set ts=2 sw=2 tw=2 :
