---
 - hosts: localhost
   roles:
     - { role: ansible-pull, tags: ['ansible-pull'] }
     - { role: nginx, tags: ['nginx'] }
     - { role: geojasper, tags: [ "geojasper" ] }
     - { role: mapgen, tags: [ "mapgen" ] }
