--- 
 - hosts: all
   roles: 
     - mapgen-data
     - nginx
     - { role: geojasper, tags: [ "geojasper" ] }
     - { role: openjpeg, tags: [ "openjpeg" ] }
     - { role: mapgen, tags: [ "mapgen" ] }
     - { role: gdal, tags: [ "gdal" ] }
     
