---
 - hosts: all
   roles:
     - { role: ansible-pull, tags: ['ansible-pull'] }
     - { role: mapgen-data, tags: ['mapgen-data'] }
     - { role: nginx, tags: ['nginx'] }
     - { role: geojasper, tags: [ 'geojasper' ] }
     - { role: mapgen, tags: [ 'mapgen' ] }
