--- 
  - name: install dependencies to compile gdal
    apt: name={{ item }}
    with_items:
      - build-essential
      - devscripts
      - autoconf
      - automake
      - autotools-dev
      - debhelper
      - fakeroot
      - file
      - lintian 
      - patch
      - patchutils
      - pbuilder

  - name: installb build-dependencies for gdal
    apt: name=gdal state=build-dep 

  - name: ensure gdal directory
    file: path=/opt/gdal state=directory

  - name: install gdal build-deps
    apt: name=gdal-bin state=build-dep
 
  - name: install gdal source
    command: apt-get source gdal-bin 
    args: 
      chdir: /opt/gdal

  - name: quilt create patch 
    shell: QUILT_PATCHES=debian/patches quilt import /opt/mapgen/ext-tool-patches/gdal.diff 
    args: 
      chdir: /opt/gdal/gdal-1.10.1+dfsg/


  - name: quilt refresh
    shell: QUILT_PATCHES=debian/patches quilt refresh
    args: 
      chdir: /opt/gdal/gdal-1.10.1+dfsg/


  - name: configure source
    command: debuild -us -uc
    args: 
      chdir: /opt/gdal/gdal-1.10.1+dfsg/
