---
- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_os_family }}.yml'
      skip: true
  tags:
    - 'role::$ROLENAME'
    - 'role::$ROLENAME:install'
    - 'role::$ROLENAME:config'

- nane: include os specific prerequisite tasks
  include: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_os_family }}.yml'
      skip: true

- include: installation.yml
  tags:
    - 'role::$ROLENAME'
    - 'role::$ROLENAME:install'
