--- 
 - name: ensure git is installed
   apt: name=git

 - name: ensure mapgen dependencies
   apt: name={{ item }}
   with_items:
     - python-cherrypy3
     - python-genshi
     - p7zip
     - gdal-bin
     - mapserver-bin

 - name: checkout git of mapgen to /opt/mapgen/
   git: dest=/opt/mapgen repo={{ mapgen_git }}
 
 - name: install systemd scripts 
   copy: name={{ item }} dest=/etc/systemd/system/{{ item }}
   with_items:
     - mapgen-web.service
     - mapgen-worker.service

 - name: reload systemd
   command: systemctl daemon-reload

 - name: enable both services and start them
   service: name={{ item }} state=started enabled=yes
   with_items:
     - mapgen-web
     - mapgen-work
