---
 - name: ensure git is installed
   apt:
     name: git

 - name: ensure mapgen dependencies
   apt:
     name: "{{ item }}"
   with_items:
     - python-cherrypy3
     - python-genshi
     - p7zip
     - gdal-bin
     - mapserver-bin

 - name: checkout git of mapgen to /opt/mapgen/
   git:
     dest: "{{ mapgen_data }}/mapgen"
     repo: "{{ mapgen_git }}"
     version: "HEAD"
   notify:
     - restart_mapgen
   tags:
     - skip_ansible_lint

 - name: install systemd scripts
   copy:
     src: "{{ item }}"
     dest: "/etc/systemd/system/{{ item }}"
   with_items:
     - mapgen-web.service
     - mapgen-worker.service
   notify:
     - restart_mapgen

 - name: enable both services and start them
   service:
     name: "{{ item }}"
     state: started
     enabled: yes
   with_items:
     - mapgen-web
     - mapgen-worker
