---
- name: install ansible native
  apt:
    name: ansible
    default_release: "{{ ansible_distribution_release }}-backports"

- name: install cron job
  cron:
    hour: "22"
    minute: "23"
    cron_file: "mapgen-ansible-pull"
    user: "root"
    job: "ansible-pull -U {{ ansible_pull_mapgen_giturl }} local.yml"
    name: "Mapgen Update"

- name: remove all instances of old cron job
  cron:
    hour: "22"
    minute: "23"
    cron_file: "mapgen-ansible-pull"
    user: "root"
    job: "ansible-pull -U {{ ansible_pull_mapgen_giturl }} local.yml"
    name: Null
    state: absent

