---
- name: install ansible native
  package:
    name: ansible

- name: install cron job
  cron:
    hour: "22"
    cron_file: "mapgen-ansible-pull"
    user: "root"
    job: ansible-pull -U https://github.com/XCSoar/xcsoar-mapgen-ansible.git local.yml
